### ISSUE TITLE
I need info and a .jar

### ISSUE THREAD

**Issue by ttk2** [WildWeazel/RealisticBiomes#1]
Does this slow down growth rates or should I do that in the bukkit.yml? 

Does it nerf bone-meal drops? if so how much?

What exactly can be grown where? Please write documentation into the github wiki.

**Comment by WildWeazel** [comment]
It doesn't slow growth or nerf bonemeal; it's an all-or nothing filter. If a plant is allowed to grow in a biome everything works as normal, otherwise all growth and bonemeal use is stopped. Currently allowed biomes are shown here: http://imgur.com/fz7AGKA
Will write all of this to the wiki.

**Comment by WildWeazel** [comment]
added jar to root level

**Comment by ttk2** [comment]
can you disable bonemeal? Or slow its spawn rate? I am going to nerf growth
rates to 10% of the original using the bukkit.yml

**Comment by WildWeazel** [comment]
Do you mean disable all bonemeal use, or turn off my bonemeal feature?

**Comment by ttk2** [comment]
I don't want bonemeal to be useful even in the appropriate biome. Or I want
it to be rare enough that it can not be used to simply grow all crops.

**Comment by WildWeazel** [comment]
All bonemeal use is disabled in the latest commit.
